--2022/03/16,蔡伯儀,Add,新增報表使用的View以及對應的Index

--drop Index IHCMD_MCS ON HCMD_MCS;
create INDEX IHCMD_MCS ON HCMD_MCS(HOSTSOURCE,HOSTDESTINATION,CMD_INSER_TIME,CMD_START_TIME,CMD_FINISH_TIME,COMMANDSTATE,CMD_ID);

--drop Index IHCMD_OHTC ON HCMD_OHTC;
create INDEX IHCMD_OHTC ON HCMD_OHTC(CMD_ID_MCS,VH_ID,CMD_STAUS,CMD_TYPE);


--DROP VIEW VHCMD_OHTC_MCS;

--要加的，但是View不能批次執行，請單獨執行下列語法
--Create VIEW VHCMD_OHTC_MCS 
--As
--Select  
--ISNULL(sbOHTC.CMD_ID_MCS,'0') As CMD_ID_MCS,
--sbOHTC.VH_ID As VH_ID,
--sbOHTC.CARRIER_ID As CARRIER_ID,
--sbMCS.HOSTSOURCE As HOSTSOURCE,
--sbMCS.HOSTDESTINATION As HOSTDESTINATION,
--sbMCS.CMD_INSER_TIME As MCS_CMD_INSER_TIME,
--sbMCS.CMD_START_TIME As MCS_CMD_START_TIME,
--sbMCS.CMD_FINISH_TIME As MCS_CMD_FINISH_TIME,
--sbMCS.COMMANDSTATE As MCS_COMMANDSTATE,
--sbOHTC.CMD_STAUS As OHTC_CMD_STATUS,
--sbOHTC.CMD_TPYE As OHTC_CMD_TYPE,
--sbOHTC.CMD_START_TIME As OHTC_CMD_START_TIME,
--sbOHTC.CMD_END_TIME As OHTC_CMD_END_TIME
--From HCMD_OHTC sbOHTC
--INNER JOIN HCMD_MCS sbMCS on sbMCS.CMD_ID = sbOHTC.CMD_ID_MCS;

--Select * from VHCMD_OHTC_MCS;




