//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectConverter_STKC_ASE_K21
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmViewExtension
    {
        public string EQPT_ID { get; set; }
        public string UNIT_NUM { get; set; }
        public string RPT_DATE_TIME { get; set; }
        public string END_TIME { get; set; }
        public string ALAM_CODE { get; set; }
        public Nullable<decimal> ALAM_LVL { get; set; }
        public decimal ALAM_STAT { get; set; }
        public string ALAM_DESC { get; set; }
        public string ERROR_ID { get; set; }
        public string UnitID { get; set; }
        public string UnitState { get; set; }
        public string RecoveryOption { get; set; }
        public string CMD_ID { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> CLASS { get; set; }
        public string ADDRESS_ID { get; set; }
        public string PORT_ID { get; set; }
        public string CARRIER_ID { get; set; }
        public Nullable<decimal> ALARM_MODULE { get; set; }
        public Nullable<decimal> IMPORTANCE_LVL { get; set; }
    }
}
