//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectConverter_STKC_ASE_K21
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALARMDATA
    {
        public string STOCKERID { get; set; }
        public decimal ALARMTYPE { get; set; }
        public string EQID { get; set; }
        public decimal ALARMSTS { get; set; }
        public string ALARMCODE { get; set; }
        public string STRDT { get; set; }
        public string ENDDT { get; set; }
        public Nullable<decimal> RECOVERTIME { get; set; }
        public Nullable<decimal> ALARMTIME { get; set; }
        public string REPORTFLAG { get; set; }
        public string ALARMLOC { get; set; }
        public string COMMANDID { get; set; }
        public string COMMANDID_RF { get; set; }
        public string CSTID { get; set; }
        public string BOXID { get; set; }
        public string CSTLOC { get; set; }
        public string SOURCE { get; set; }
        public string DEST { get; set; }
        public string STOCKERUNITSTATUS { get; set; }
        public string STOCKERCRANEID { get; set; }
        public string MPLCALARMINDEX { get; set; }
        public string PLCDOOROPENDT { get; set; }
        public string PLCDOORCLOSEDDT { get; set; }
        public string PLCRESETALARMDT { get; set; }
        public string SRSEQ { get; set; }
    }
}
