//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectConverter_STKC_ASE_K21
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmDataExtension
    {
        public string STOCKERID { get; set; }
        public string EQID { get; set; }
        public decimal ALARMSTS { get; set; }
        public string ALARMCODE { get; set; }
        public string STRDT { get; set; }
        public Nullable<decimal> CLASS { get; set; }
        public Nullable<decimal> ALARM_MODULE { get; set; }
        public Nullable<decimal> IMPORTANCE_LVL { get; set; }
        public string REMARK { get; set; }
    }
}
