using com.mirle.ibg3k0.ohxc.wpf.App;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using ViewerObject;

namespace ControlSystemViewer.Views.CurrentDataGrid
{
    /// <summary>
    /// uc_grid_CurAlarm.xaml 的互動邏輯
    /// </summary>
    public partial class uc_grid_CurAlarm : UserControl
    {
        WindownApplication app = null;
        public uc_grid_CurAlarm()
        {
            InitializeComponent();
        }

        private void grid_Cur_Alarm_AutoGeneratedColumns(object sender, EventArgs e)
        {
            try
            {
                //string headername= (DataGridAutoGeneratingColumnEventArgs)e
                foreach (DataGridColumn dc in ((DataGrid)sender).Columns)
                {
                    switch (dc.Header.ToString())
                    {

                        case nameof(VALARM._RPT_DATE_TIME):
                            dc.Visibility = Visibility.Collapsed;
                            break;

                        default:
                            break;
                    }

                }
            }
            catch (Exception ex)
            {
               
            }
        }
    }
}
