// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agvmessage.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace com.mirle.ibg3k0.sc.ProtocolFormat.NorthInnolux.Agvmessage {

  /// <summary>Holder for reflection information generated from agvmessage.proto</summary>
  public static partial class AgvmessageReflection {

    #region Descriptor
    /// <summary>File descriptor for agvmessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AgvmessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBhZ3ZtZXNzYWdlLnByb3RvEgh0dXRvcmlhbCJvCiRJRF8zNl9UUkFOU19F",
            "VkVOVF9SRVNQT05TRV9FWFRFTlNJT04SFgoORGVzdGluYXRpb25BZHIYASAB",
            "KAkSFgoOR3VpZGVfU2VjdGlvbnMYAiADKAkSFwoPR3VpZGVfQWRkcmVzc2Vz",
            "GAMgAygJQp4BChRjb20uZXhhbXBsZS50dXRvcmlhbEIRQWRkcmVzc0Jvb2tQ",
            "cm90b3NQAVorZ2l0aHViLmNvbS9nb2xhbmcvcHJvdG9idWYvcHR5cGVzL3Rp",
            "bWVzdGFtcPgBAaICA0dQQqoCOmNvbS5taXJsZS5pYmczazAuc2MuUHJvdG9j",
            "b2xGb3JtYXQuTm9ydGhJbm5vbHV4LkFndm1lc3NhZ2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::com.mirle.ibg3k0.sc.ProtocolFormat.NorthInnolux.Agvmessage.ID_36_TRANS_EVENT_RESPONSE_EXTENSION), global::com.mirle.ibg3k0.sc.ProtocolFormat.NorthInnolux.Agvmessage.ID_36_TRANS_EVENT_RESPONSE_EXTENSION.Parser, new[]{ "DestinationAdr", "GuideSections", "GuideAddresses" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ID_36_TRANS_EVENT_RESPONSE_EXTENSION : pb::IMessage<ID_36_TRANS_EVENT_RESPONSE_EXTENSION> {
    private static readonly pb::MessageParser<ID_36_TRANS_EVENT_RESPONSE_EXTENSION> _parser = new pb::MessageParser<ID_36_TRANS_EVENT_RESPONSE_EXTENSION>(() => new ID_36_TRANS_EVENT_RESPONSE_EXTENSION());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ID_36_TRANS_EVENT_RESPONSE_EXTENSION> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.mirle.ibg3k0.sc.ProtocolFormat.NorthInnolux.Agvmessage.AgvmessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ID_36_TRANS_EVENT_RESPONSE_EXTENSION() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ID_36_TRANS_EVENT_RESPONSE_EXTENSION(ID_36_TRANS_EVENT_RESPONSE_EXTENSION other) : this() {
      destinationAdr_ = other.destinationAdr_;
      guideSections_ = other.guideSections_.Clone();
      guideAddresses_ = other.guideAddresses_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ID_36_TRANS_EVENT_RESPONSE_EXTENSION Clone() {
      return new ID_36_TRANS_EVENT_RESPONSE_EXTENSION(this);
    }

    /// <summary>Field number for the "DestinationAdr" field.</summary>
    public const int DestinationAdrFieldNumber = 1;
    private string destinationAdr_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DestinationAdr {
      get { return destinationAdr_; }
      set {
        destinationAdr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Guide_Sections" field.</summary>
    public const int GuideSectionsFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_guideSections_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> guideSections_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> GuideSections {
      get { return guideSections_; }
    }

    /// <summary>Field number for the "Guide_Addresses" field.</summary>
    public const int GuideAddressesFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_guideAddresses_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> guideAddresses_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> GuideAddresses {
      get { return guideAddresses_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ID_36_TRANS_EVENT_RESPONSE_EXTENSION);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ID_36_TRANS_EVENT_RESPONSE_EXTENSION other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DestinationAdr != other.DestinationAdr) return false;
      if(!guideSections_.Equals(other.guideSections_)) return false;
      if(!guideAddresses_.Equals(other.guideAddresses_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DestinationAdr.Length != 0) hash ^= DestinationAdr.GetHashCode();
      hash ^= guideSections_.GetHashCode();
      hash ^= guideAddresses_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DestinationAdr.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DestinationAdr);
      }
      guideSections_.WriteTo(output, _repeated_guideSections_codec);
      guideAddresses_.WriteTo(output, _repeated_guideAddresses_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DestinationAdr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DestinationAdr);
      }
      size += guideSections_.CalculateSize(_repeated_guideSections_codec);
      size += guideAddresses_.CalculateSize(_repeated_guideAddresses_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ID_36_TRANS_EVENT_RESPONSE_EXTENSION other) {
      if (other == null) {
        return;
      }
      if (other.DestinationAdr.Length != 0) {
        DestinationAdr = other.DestinationAdr;
      }
      guideSections_.Add(other.guideSections_);
      guideAddresses_.Add(other.guideAddresses_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            DestinationAdr = input.ReadString();
            break;
          }
          case 18: {
            guideSections_.AddEntriesFrom(input, _repeated_guideSections_codec);
            break;
          }
          case 26: {
            guideAddresses_.AddEntriesFrom(input, _repeated_guideAddresses_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
